Controllers/EmergencyController.cs
using EmployeeDotNet8.Data;
using EmployeeDotNet8.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeDotNet8.Controllers
{
    public class EmergencyController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmergencyController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View( await _context.emergencies.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Emergency model)
        {
            if (ModelState.IsValid)
            {
                _context.emergencies.Add(model);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var db = await _context.emergencies.FindAsync(id);
            if (db == null)
            {
                return BadRequest();
            }
            return View(db);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Emergency model)
        {
            if (ModelState.IsValid)
            {
                _context.emergencies.Update(model);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var db = await _context.emergencies.FindAsync(id);

            if(db == null)
            {
                return NotFound();
            }

            _context.emergencies.Remove(db);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/EmployeeController.cs
using EmployeeDotNet8.Data;
using EmployeeDotNet8.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static EmployeeDotNet8.Models.Employee;

namespace EmployeeDotNet8.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeeController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Menu()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View(_context.Employees.ToList());
        }

        public IActionResult AddEmployees()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEmployees(Employee model)
        {
            if (ModelState.IsValid)
            {
               _context.Employees.Add(model);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var db = await _context.Employees.FindAsync(id);
            if (db == null)
            {
                return NotFound();
            }
            return View(db);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Employee model)
        {
            if (ModelState.IsValid)
            {
                _context.Employees.Update(model);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var db = await _context.Employees.FindAsync(id);
            if (db == null)
            {
                return NotFound();
            }

            _context.Employees.Remove(db);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/TodoListController.cs
using EmployeeDotNet8.Data;
using EmployeeDotNet8.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeDotNet8.Controllers
{
    public class TodoListController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TodoListController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Add()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Todolist.ToListAsync());
        }

        public IActionResult create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> create(Todolist model)
        {
            if (ModelState.IsValid)
            {
                _context.Todolist.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var db = await _context.Todolist.FindAsync(id);
            if(db == null)
            {
                return BadRequest();
            }
            return View(db);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Todolist model)
        {
            if (ModelState.IsValid)
            {
                _context.Todolist.Update(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var db = await _context.Todolist.FindAsync(id);
            if (db == null)
            {
                return NotFound();
            }

            _context.Todolist.Remove(db);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeDotNet8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeDotNet8.styles.css" asp-append-version="true" />
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid d-flex gap-2">
                <a class="navbar-brand" asp-area="" asp-controller="Employee" asp-action="Menu"><img src="/home.png" width="45" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 gap-2">
                        <li class="nav-item d-flex align-items-lg-center">
                            <div>
                                <img src="/employee.png" width="20" />
                            </div>
                            <div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">ข้อมูลพนักงาน</a>
                            </div>
                        </li>
                        <li class="nav-item d-flex align-items-lg-center">
                            <div>
                                <img src="/idea.png" width="20" />
                            </div>
                            <div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="TodoList" asp-action="Index">ข้อมูล Todolist</a>
                            </div>
                        </li>
                        <li class="nav-item d-flex align-items-lg-center">
                            <div>
                                <img src="/analysis.png" width="20" />
                            </div>
                            <div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Emergency" asp-action="Index">ข้อมูลรับแจ้งเหตุ</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white">
        <div class="container">
            &copy; 2567 - Arnon Boonyayothin 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>